# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cityofLA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   pod 'AWSMobileClient', '~> 2.6.13'
   pod 'AWSPinpoint', '~> 2.6.13'
   pod 'GoogleMaps'
   pod 'GooglePlaces'
   pod 'FMDB'
   pod 'IQKeyboardManager'
   pod 'SVProgressHUD', '~> 2.1'
end
